version: 2.1

jobs:
  test:
    machine:
      enabled: true
      # image: ubuntu-1604:201903-01
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup Docker Compose
          command: |
            sudo apt-get -qq update -y
            sudo apt-get -q install -y curl ca-certificates make
            make setup
      - run:
          name: Test
          command: |
            # sudo docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            make test VERBOSE=1

workflows:
  version: 2
  build_and_package:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              # only: master
              only: /.*/
