FROM debian:buster

RUN apt-get -qq update
RUN apt-get -q install -y python wget
RUN set -x; \
    wget -q https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py ;\
	python /tmp/get-pip.py
RUN apt-get -q install -y python-opencv

WORKDIR /usr/src/app
ADD read_camera.py ./
ADD *.jpg ./
RUN pip install redis

CMD [ "python", "./read_camera.py" ]
