name: Animal Recognition Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install redis-cli
      run: |
          cd ..;
          git clone https://github.com/redis/redis.git;
          cd redis;
          git checkout 6.2.7;
          make -j$(nproc) redis-cli;
          alias redis-cli="`pwd`/src/redis-cli";
          redis-cli SET installation succeeded 
    - name: Test 
      run: make test VERBOSE=1
